baseURL = 'https://rsclarke.dev/'
languageCode = 'en-us'
title = 'Richard Clarke (@rsclarke)'
disableKinds = ["RSS", "taxonomy", "term"]

[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'
