version: "3"

tasks:
  build:
    cmds:
      - hugo

  serve:
    cmds:
      - hugo serve

  clean:
    cmds:
      - rm -rf public .hugo_build.lock hugo_stats.json .wrangler

  publish:
    deps: [build]
    cmds:
      - npx wrangler pages deploy --project-name="rsclarke" ./public
